name: Build Cron Schedule

on:
  schedule:
    # Every ten minutes on Fridays
    - cron: '*/10 * * * 5'

jobs:
  build:
    name: Netlify Build Hook
    runs-on: ubuntu-latest
    steps:
      - name: cURL Request
        env:
          NETLIFY_BUILD_HOOK: ${{ secrets.NetlifyBuildHook }}
        run: curl -X POST -d {} "${NETLIFY_BUILD_HOOK}"
