name: Build Cron Schedule

on:
  schedule:
    # A few minutes before the hour mark on Fridays (GMT)
    - cron: '50 10-22 * * 5'

jobs:
  build:
    name: Netlify Build Hook
    runs-on: ubuntu-latest
    steps:
      - name: cURL Request
        env:
          NETLIFY_BUILD_HOOK: ${{ secrets.NetlifyBuildHook }}
        run: curl -X POST -d {} "${NETLIFY_BUILD_HOOK}"
